<section class="container">
    <div class="row">
        <div class="six columns">
            <label for="user_countries_id">Country</label>
            <?= Form::select(
                'user.countries_id', //Field name, using 'user' of example
                Countries::all(), //Data
                'class="js-remote" data-url="getRegions/" data-update="div_regions"', //
                null, //For now it has no default value
                '- Select -', //Shows a empty vale
                'id',  //Value of the option
                'name' //Name to show
            ); ?>
        </div>
    </div>
    <div class="row">
        <div class="six columns">
            <label for="user_region_id">Region</label>
            <div id='div_regions'>
                <select disabled></select>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="six columns">
            <label for="user_city_id">City</label>
            <div id='div_cities'>
                <select disabled></select>
            </div>
        </div>
    </div>
</section>