<section class="container">
    <div class="row">
        <div class="six columns">
            <label for="user_countries_id">Country</label>
            <?= Form::select(
                'user.countries_id', //Field name, using 'user' of example
                $data, //Data
                'class="js-remote" data-url="/kumbia_js/get/regions/" data-update="user_regions_id"', //
                null, //For now it has no default value
                '- Select -', //Shows a empty vale
                'id',  //Value of the option
                'name' //Name to show
            ); ?>
        </div>
    </div>
    <div class="row">
        <div class="six columns">
            <label for="user_regions_id">Region</label>
            <?= Form::select(
                'user.regions_id',
                [],
                'disabled class="js-remote" data-url="kumbia_js/get/cities/" data-update="user_cities_id"',
            ); ?>
        </div>
    </div>
    <div class="row">
        <div class="six columns">
            <label for="user_cities_id">City</label>
            <?= Form::select(
                'user.cities_id',
                [],
                'disabled'
            ); ?>
        </div>
    </div>
</section>