<header>
    <div class="row container-top">
        <h1>KumbiaPHP Javascript</h1>
        <p>Uses kumbiaphp.js</p>
    </div>
</header>
<section class="container">
    <div class="row">
        <div class="four columns">
            <ul>
                <li><a href="kumbia_js/dependent_select" class="js-remote" data-to="load-content">Dependet select</a></li>
            </ul>
        </div>
        <div id="load-content" class="eight columns">

        </div>
    </div>
</section>